package com.acme;

import com.acme.details.AbstractStatusDetailDecorator;
import com.acme.details.DetailsFacadeConcrete;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Standard main class for Spring, generated by Spring ####template
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
        AbstractStatusDetailDecorator.setFacade(new DetailsFacadeConcrete());
    }
}
